"""
Data model for Obsidian project workspaces
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, List
from uuid import uuid4


@dataclass
class ObsidianNote:
    """Represents a single Obsidian note/file"""
    id: str = field(default_factory=lambda: str(uuid4()))
    filename: str = ""  # e.g., "README.md", "Task_Progress.md"
    path: str = ""  # Relative path in workspace
    content: str = ""  # Markdown content
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)

    def update_content(self, new_content: str) -> None:
        """Update note content"""
        self.content = new_content
        self.updated_at = datetime.now()


@dataclass
class WorkspaceFolder:
    """Represents a folder in the workspace"""
    name: str = ""  # Folder name
    path: str = ""  # Relative path
    description: str = ""  # What goes in this folder
    notes: List[ObsidianNote] = field(default_factory=list)
    subfolders: List['WorkspaceFolder'] = field(default_factory=list)

    def add_note(self, note: ObsidianNote) -> None:
        """Add a note to this folder"""
        self.notes.append(note)

    def add_subfolder(self, subfolder: 'WorkspaceFolder') -> None:
        """Add a subfolder"""
        self.subfolders.append(subfolder)


@dataclass
class ProjectWorkspace:
    """
    Complete Obsidian project workspace structure
    Generated by WorkspaceGenerator
    """
    id: str = field(default_factory=lambda: str(uuid4()))
    project_name: str = ""
    workspace_root_path: str = ""  # Full path to workspace folder

    # Root-level files
    roadmap_note: Optional[ObsidianNote] = None
    task_progress_note: Optional[ObsidianNote] = None
    coach_log_note: Optional[ObsidianNote] = None

    # Folder structure
    resources_folder: Optional[WorkspaceFolder] = None
    notes_folder: Optional[WorkspaceFolder] = None
    data_folder: Optional[WorkspaceFolder] = None
    archive_folder: Optional[WorkspaceFolder] = None

    # Metadata
    created_at: datetime = field(default_factory=datetime.now)
    last_synced_at: Optional[datetime] = None

    # Status
    is_initialized: bool = False  # Workspace created on disk?

    def get_all_notes(self) -> List[ObsidianNote]:
        """Get all notes in workspace"""
        notes = []
        if self.roadmap_note:
            notes.append(self.roadmap_note)
        if self.task_progress_note:
            notes.append(self.task_progress_note)
        if self.coach_log_note:
            notes.append(self.coach_log_note)

        def collect_folder_notes(folder: WorkspaceFolder) -> None:
            notes.extend(folder.notes)
            for subfolder in folder.subfolders:
                collect_folder_notes(subfolder)

        if self.resources_folder:
            collect_folder_notes(self.resources_folder)
        if self.notes_folder:
            collect_folder_notes(self.notes_folder)
        if self.data_folder:
            collect_folder_notes(self.data_folder)
        if self.archive_folder:
            collect_folder_notes(self.archive_folder)

        return notes

    def update_roadmap_note(self, content: str) -> None:
        """Update roadmap note"""
        if self.roadmap_note:
            self.roadmap_note.update_content(content)
        self.last_synced_at = datetime.now()

    def update_progress_note(self, content: str) -> None:
        """Update progress note"""
        if self.task_progress_note:
            self.task_progress_note.update_content(content)
        self.last_synced_at = datetime.now()

    def update_coach_log(self, content: str) -> None:
        """Update coach log"""
        if self.coach_log_note:
            self.coach_log_note.update_content(content)
        self.last_synced_at = datetime.now()

    def to_dict(self) -> dict:
        """Convert to dictionary"""
        return {
            'id': self.id,
            'project_name': self.project_name,
            'workspace_root_path': self.workspace_root_path,
            'is_initialized': self.is_initialized,
            'total_notes': len(self.get_all_notes()),
            'created_at': self.created_at.isoformat(),
            'last_synced_at': self.last_synced_at.isoformat()
            if self.last_synced_at else None,
        }


# Template folder structures for different project types
WORKSPACE_TEMPLATES = {
    "learning": {
        "structure": {
            "📋 Roadmap.md": "Your approved learning outline",
            "📊 Task Progress.md": "Micro-tasks and completion status",
            "📚 Resources/": "Learning materials and links",
            "📝 Notes/": "Your learning notes by topic",
            "🎯 Exercises/": "Code/problem solutions",
            "🤖 Coach Log.md": "AI coaching feedback",
        }
    },
    "research": {
        "structure": {
            "📋 Roadmap.md": "Research phases and milestones",
            "📊 Task Progress.md": "Experiments and analysis tasks",
            "📚 Literature/": "Papers and references",
            "📝 Notes/": "Research findings and insights",
            "📁 Data/": "Datasets and results (git-ignored)",
            "🤖 Coach Log.md": "Research coaching feedback",
        }
    },
    "job_hunting": {
        "structure": {
            "📋 Roadmap.md": "Job search strategy and timeline",
            "📊 Task Progress.md": "Applications, interviews, prep",
            "📚 Resources/": "Job boards, resume tips, interview guides",
            "📝 Notes/": "Company research, interview prep notes",
            "📁 Applications/": "Companies, positions, status",
            "🤖 Coach Log.md": "Job search coaching",
        }
    },
    "startup": {
        "structure": {
            "📋 Roadmap.md": "Business plan and launch timeline",
            "📊 Task Progress.md": "Development, marketing, operations",
            "📚 Resources/": "Market research, funding guides, tools",
            "📝 Notes/": "Ideas, validations, decisions",
            "📁 Data/": "Metrics, user feedback, financials",
            "🤖 Coach Log.md": "Startup coaching",
        }
    },
}
